export const SET_FILTER = 'SET_FILTER';
export const SET_SHOW_STATIC_DATA = 'SET_SHOW_STATIC_DATA';

export const SEARCH_REQUEST_STARTED = 'SEARCH_REQUEST_STARTED';
export const RECIEVE_SEARCH_RESPONSE = 'RECIEVE_SEARCH_RESPONSE';
export const SEARCH_ERROR = 'SEARCH_ERROR';
